FROM node:20

ENV CHOKIDAR_USEPOLLING=true
ENV ROLLUP_USE_NODE_BIN=false

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --no-optional

COPY . .

EXPOSE 5173
CMD ["yarn", "dev", "--host", "0.0.0.0", "--port", "5000"]
