version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: ../Dockerfile.server
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"
    networks:
      - dev

  ui:
    build:
      context: ./ui
      dockerfile: ../Dockerfile.ui
    platform: linux/amd64
    volumes:
      # 1) bring in the source tree from macOS
      - ./ui:/app:cached # :cached = faster on macOS
      # 2) hide host node_modules with its own volume
      - ui_node_modules:/app/node_modules
    ports:
      - "5173:5173" # or 3000 for CRA
    networks:
      - dev
    environment:
      - CHOKIDAR_USEPOLLING=true # for file watching inside Docker
      - ROLLUP_USE_NODE_BIN=false
    command: sh -c "yarn install --frozen-lockfile && yarn dev --host 0.0.0.0 --port 5173"

networks:
  dev:
    driver: bridge

volumes:
  ui_node_modules:
